// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roborio_message.proto

package frc2020.proto;

public final class RoborioMessage {
  private RoborioMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RioUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:frc2020.proto.RioUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     * @return Whether the odometryUpdate field is set.
     */
    boolean hasOdometryUpdate();
    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     * @return The odometryUpdate.
     */
    frc2020.proto.RoborioMessage.WheelOdometryUpdate getOdometryUpdate();
    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     */
    frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder getOdometryUpdateOrBuilder();
  }
  /**
   * Protobuf type {@code frc2020.proto.RioUpdate}
   */
  public  static final class RioUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:frc2020.proto.RioUpdate)
      RioUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RioUpdate.newBuilder() to construct.
    private RioUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RioUpdate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RioUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RioUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder subBuilder = null;
              if (odometryUpdate_ != null) {
                subBuilder = odometryUpdate_.toBuilder();
              }
              odometryUpdate_ = input.readMessage(frc2020.proto.RoborioMessage.WheelOdometryUpdate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(odometryUpdate_);
                odometryUpdate_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_RioUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_RioUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frc2020.proto.RoborioMessage.RioUpdate.class, frc2020.proto.RoborioMessage.RioUpdate.Builder.class);
    }

    public static final int ODOMETRY_UPDATE_FIELD_NUMBER = 1;
    private frc2020.proto.RoborioMessage.WheelOdometryUpdate odometryUpdate_;
    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     * @return Whether the odometryUpdate field is set.
     */
    public boolean hasOdometryUpdate() {
      return odometryUpdate_ != null;
    }
    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     * @return The odometryUpdate.
     */
    public frc2020.proto.RoborioMessage.WheelOdometryUpdate getOdometryUpdate() {
      return odometryUpdate_ == null ? frc2020.proto.RoborioMessage.WheelOdometryUpdate.getDefaultInstance() : odometryUpdate_;
    }
    /**
     * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
     */
    public frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder getOdometryUpdateOrBuilder() {
      return getOdometryUpdate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (odometryUpdate_ != null) {
        output.writeMessage(1, getOdometryUpdate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (odometryUpdate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOdometryUpdate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frc2020.proto.RoborioMessage.RioUpdate)) {
        return super.equals(obj);
      }
      frc2020.proto.RoborioMessage.RioUpdate other = (frc2020.proto.RoborioMessage.RioUpdate) obj;

      if (hasOdometryUpdate() != other.hasOdometryUpdate()) return false;
      if (hasOdometryUpdate()) {
        if (!getOdometryUpdate()
            .equals(other.getOdometryUpdate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOdometryUpdate()) {
        hash = (37 * hash) + ODOMETRY_UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getOdometryUpdate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.RioUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frc2020.proto.RoborioMessage.RioUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code frc2020.proto.RioUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:frc2020.proto.RioUpdate)
        frc2020.proto.RoborioMessage.RioUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_RioUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_RioUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frc2020.proto.RoborioMessage.RioUpdate.class, frc2020.proto.RoborioMessage.RioUpdate.Builder.class);
      }

      // Construct using frc2020.proto.RoborioMessage.RioUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (odometryUpdateBuilder_ == null) {
          odometryUpdate_ = null;
        } else {
          odometryUpdate_ = null;
          odometryUpdateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_RioUpdate_descriptor;
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.RioUpdate getDefaultInstanceForType() {
        return frc2020.proto.RoborioMessage.RioUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.RioUpdate build() {
        frc2020.proto.RoborioMessage.RioUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.RioUpdate buildPartial() {
        frc2020.proto.RoborioMessage.RioUpdate result = new frc2020.proto.RoborioMessage.RioUpdate(this);
        if (odometryUpdateBuilder_ == null) {
          result.odometryUpdate_ = odometryUpdate_;
        } else {
          result.odometryUpdate_ = odometryUpdateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frc2020.proto.RoborioMessage.RioUpdate) {
          return mergeFrom((frc2020.proto.RoborioMessage.RioUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frc2020.proto.RoborioMessage.RioUpdate other) {
        if (other == frc2020.proto.RoborioMessage.RioUpdate.getDefaultInstance()) return this;
        if (other.hasOdometryUpdate()) {
          mergeOdometryUpdate(other.getOdometryUpdate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frc2020.proto.RoborioMessage.RioUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frc2020.proto.RoborioMessage.RioUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private frc2020.proto.RoborioMessage.WheelOdometryUpdate odometryUpdate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          frc2020.proto.RoborioMessage.WheelOdometryUpdate, frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder, frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder> odometryUpdateBuilder_;
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       * @return Whether the odometryUpdate field is set.
       */
      public boolean hasOdometryUpdate() {
        return odometryUpdateBuilder_ != null || odometryUpdate_ != null;
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       * @return The odometryUpdate.
       */
      public frc2020.proto.RoborioMessage.WheelOdometryUpdate getOdometryUpdate() {
        if (odometryUpdateBuilder_ == null) {
          return odometryUpdate_ == null ? frc2020.proto.RoborioMessage.WheelOdometryUpdate.getDefaultInstance() : odometryUpdate_;
        } else {
          return odometryUpdateBuilder_.getMessage();
        }
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public Builder setOdometryUpdate(frc2020.proto.RoborioMessage.WheelOdometryUpdate value) {
        if (odometryUpdateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          odometryUpdate_ = value;
          onChanged();
        } else {
          odometryUpdateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public Builder setOdometryUpdate(
          frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder builderForValue) {
        if (odometryUpdateBuilder_ == null) {
          odometryUpdate_ = builderForValue.build();
          onChanged();
        } else {
          odometryUpdateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public Builder mergeOdometryUpdate(frc2020.proto.RoborioMessage.WheelOdometryUpdate value) {
        if (odometryUpdateBuilder_ == null) {
          if (odometryUpdate_ != null) {
            odometryUpdate_ =
              frc2020.proto.RoborioMessage.WheelOdometryUpdate.newBuilder(odometryUpdate_).mergeFrom(value).buildPartial();
          } else {
            odometryUpdate_ = value;
          }
          onChanged();
        } else {
          odometryUpdateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public Builder clearOdometryUpdate() {
        if (odometryUpdateBuilder_ == null) {
          odometryUpdate_ = null;
          onChanged();
        } else {
          odometryUpdate_ = null;
          odometryUpdateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder getOdometryUpdateBuilder() {
        
        onChanged();
        return getOdometryUpdateFieldBuilder().getBuilder();
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      public frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder getOdometryUpdateOrBuilder() {
        if (odometryUpdateBuilder_ != null) {
          return odometryUpdateBuilder_.getMessageOrBuilder();
        } else {
          return odometryUpdate_ == null ?
              frc2020.proto.RoborioMessage.WheelOdometryUpdate.getDefaultInstance() : odometryUpdate_;
        }
      }
      /**
       * <code>.frc2020.proto.WheelOdometryUpdate odometry_update = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          frc2020.proto.RoborioMessage.WheelOdometryUpdate, frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder, frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder> 
          getOdometryUpdateFieldBuilder() {
        if (odometryUpdateBuilder_ == null) {
          odometryUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              frc2020.proto.RoborioMessage.WheelOdometryUpdate, frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder, frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder>(
                  getOdometryUpdate(),
                  getParentForChildren(),
                  isClean());
          odometryUpdate_ = null;
        }
        return odometryUpdateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:frc2020.proto.RioUpdate)
    }

    // @@protoc_insertion_point(class_scope:frc2020.proto.RioUpdate)
    private static final frc2020.proto.RoborioMessage.RioUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frc2020.proto.RoborioMessage.RioUpdate();
    }

    public static frc2020.proto.RoborioMessage.RioUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RioUpdate>
        PARSER = new com.google.protobuf.AbstractParser<RioUpdate>() {
      @java.lang.Override
      public RioUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RioUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RioUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RioUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frc2020.proto.RoborioMessage.RioUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WheelOdometryUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:frc2020.proto.WheelOdometryUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float time_stamp = 1;</code>
     * @return The timeStamp.
     */
    float getTimeStamp();

    /**
     * <code>float left = 2;</code>
     * @return The left.
     */
    float getLeft();

    /**
     * <code>float right = 3;</code>
     * @return The right.
     */
    float getRight();
  }
  /**
   * Protobuf type {@code frc2020.proto.WheelOdometryUpdate}
   */
  public  static final class WheelOdometryUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:frc2020.proto.WheelOdometryUpdate)
      WheelOdometryUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WheelOdometryUpdate.newBuilder() to construct.
    private WheelOdometryUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WheelOdometryUpdate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WheelOdometryUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WheelOdometryUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              timeStamp_ = input.readFloat();
              break;
            }
            case 21: {

              left_ = input.readFloat();
              break;
            }
            case 29: {

              right_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_WheelOdometryUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_WheelOdometryUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frc2020.proto.RoborioMessage.WheelOdometryUpdate.class, frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder.class);
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 1;
    private float timeStamp_;
    /**
     * <code>float time_stamp = 1;</code>
     * @return The timeStamp.
     */
    public float getTimeStamp() {
      return timeStamp_;
    }

    public static final int LEFT_FIELD_NUMBER = 2;
    private float left_;
    /**
     * <code>float left = 2;</code>
     * @return The left.
     */
    public float getLeft() {
      return left_;
    }

    public static final int RIGHT_FIELD_NUMBER = 3;
    private float right_;
    /**
     * <code>float right = 3;</code>
     * @return The right.
     */
    public float getRight() {
      return right_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeStamp_ != 0F) {
        output.writeFloat(1, timeStamp_);
      }
      if (left_ != 0F) {
        output.writeFloat(2, left_);
      }
      if (right_ != 0F) {
        output.writeFloat(3, right_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeStamp_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, timeStamp_);
      }
      if (left_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, left_);
      }
      if (right_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, right_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frc2020.proto.RoborioMessage.WheelOdometryUpdate)) {
        return super.equals(obj);
      }
      frc2020.proto.RoborioMessage.WheelOdometryUpdate other = (frc2020.proto.RoborioMessage.WheelOdometryUpdate) obj;

      if (java.lang.Float.floatToIntBits(getTimeStamp())
          != java.lang.Float.floatToIntBits(
              other.getTimeStamp())) return false;
      if (java.lang.Float.floatToIntBits(getLeft())
          != java.lang.Float.floatToIntBits(
              other.getLeft())) return false;
      if (java.lang.Float.floatToIntBits(getRight())
          != java.lang.Float.floatToIntBits(
              other.getRight())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTimeStamp());
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLeft());
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRight());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frc2020.proto.RoborioMessage.WheelOdometryUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code frc2020.proto.WheelOdometryUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:frc2020.proto.WheelOdometryUpdate)
        frc2020.proto.RoborioMessage.WheelOdometryUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_WheelOdometryUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_WheelOdometryUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frc2020.proto.RoborioMessage.WheelOdometryUpdate.class, frc2020.proto.RoborioMessage.WheelOdometryUpdate.Builder.class);
      }

      // Construct using frc2020.proto.RoborioMessage.WheelOdometryUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timeStamp_ = 0F;

        left_ = 0F;

        right_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frc2020.proto.RoborioMessage.internal_static_frc2020_proto_WheelOdometryUpdate_descriptor;
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.WheelOdometryUpdate getDefaultInstanceForType() {
        return frc2020.proto.RoborioMessage.WheelOdometryUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.WheelOdometryUpdate build() {
        frc2020.proto.RoborioMessage.WheelOdometryUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frc2020.proto.RoborioMessage.WheelOdometryUpdate buildPartial() {
        frc2020.proto.RoborioMessage.WheelOdometryUpdate result = new frc2020.proto.RoborioMessage.WheelOdometryUpdate(this);
        result.timeStamp_ = timeStamp_;
        result.left_ = left_;
        result.right_ = right_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frc2020.proto.RoborioMessage.WheelOdometryUpdate) {
          return mergeFrom((frc2020.proto.RoborioMessage.WheelOdometryUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frc2020.proto.RoborioMessage.WheelOdometryUpdate other) {
        if (other == frc2020.proto.RoborioMessage.WheelOdometryUpdate.getDefaultInstance()) return this;
        if (other.getTimeStamp() != 0F) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.getLeft() != 0F) {
          setLeft(other.getLeft());
        }
        if (other.getRight() != 0F) {
          setRight(other.getRight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frc2020.proto.RoborioMessage.WheelOdometryUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frc2020.proto.RoborioMessage.WheelOdometryUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float timeStamp_ ;
      /**
       * <code>float time_stamp = 1;</code>
       * @return The timeStamp.
       */
      public float getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>float time_stamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(float value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float time_stamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0F;
        onChanged();
        return this;
      }

      private float left_ ;
      /**
       * <code>float left = 2;</code>
       * @return The left.
       */
      public float getLeft() {
        return left_;
      }
      /**
       * <code>float left = 2;</code>
       * @param value The left to set.
       * @return This builder for chaining.
       */
      public Builder setLeft(float value) {
        
        left_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float left = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeft() {
        
        left_ = 0F;
        onChanged();
        return this;
      }

      private float right_ ;
      /**
       * <code>float right = 3;</code>
       * @return The right.
       */
      public float getRight() {
        return right_;
      }
      /**
       * <code>float right = 3;</code>
       * @param value The right to set.
       * @return This builder for chaining.
       */
      public Builder setRight(float value) {
        
        right_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float right = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRight() {
        
        right_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:frc2020.proto.WheelOdometryUpdate)
    }

    // @@protoc_insertion_point(class_scope:frc2020.proto.WheelOdometryUpdate)
    private static final frc2020.proto.RoborioMessage.WheelOdometryUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frc2020.proto.RoborioMessage.WheelOdometryUpdate();
    }

    public static frc2020.proto.RoborioMessage.WheelOdometryUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WheelOdometryUpdate>
        PARSER = new com.google.protobuf.AbstractParser<WheelOdometryUpdate>() {
      @java.lang.Override
      public WheelOdometryUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WheelOdometryUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WheelOdometryUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WheelOdometryUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frc2020.proto.RoborioMessage.WheelOdometryUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc2020_proto_RioUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc2020_proto_RioUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_frc2020_proto_WheelOdometryUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_frc2020_proto_WheelOdometryUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025roborio_message.proto\022\rfrc2020.proto\"H" +
      "\n\tRioUpdate\022;\n\017odometry_update\030\001 \001(\0132\".f" +
      "rc2020.proto.WheelOdometryUpdate\"F\n\023Whee" +
      "lOdometryUpdate\022\022\n\ntime_stamp\030\001 \001(\002\022\014\n\004l" +
      "eft\030\002 \001(\002\022\r\n\005right\030\003 \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_frc2020_proto_RioUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_frc2020_proto_RioUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc2020_proto_RioUpdate_descriptor,
        new java.lang.String[] { "OdometryUpdate", });
    internal_static_frc2020_proto_WheelOdometryUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_frc2020_proto_WheelOdometryUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_frc2020_proto_WheelOdometryUpdate_descriptor,
        new java.lang.String[] { "TimeStamp", "Left", "Right", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
