# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jetson_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jetson_message.proto',
  package='frc2020.networking',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14jetson_message.proto\x12\x12\x66rc2020.networking\"\xb9\x01\n\x0cJetsonUpdate\x12?\n\x0etarget_updates\x18\x01 \x01(\x0b\x32\'.frc2020.networking.VisionTargetsUpdate\x12\x31\n\x0bslam_update\x18\x02 \x01(\x0b\x32\x1c.frc2020.networking.SLAMPose\x12\x35\n\x0c\x64rive_signal\x18\x03 \x01(\x0b\x32\x1f.frc2020.networking.DriveSignal\"\xa5\x01\n\x13VisionTargetsUpdate\x12\x45\n\x07targets\x18\x01 \x03(\x0b\x32\x34.frc2020.networking.VisionTargetsUpdate.VisionTarget\x1aG\n\x0cVisionTarget\x12\x12\n\nframe_epoc\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05theta\x18\x04 \x01(\x02\"D\n\x08SLAMPose\x12\x13\n\x0bupdate_epoc\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05theta\x18\x04 \x01(\x02\"\xa3\x01\n\x0b\x44riveSignal\x12\x13\n\x0b\x64\x65mand_left\x18\x01 \x01(\x02\x12\x14\n\x0c\x64\x65mand_right\x18\x02 \x01(\x02\x12?\n\x0b\x64\x65mand_type\x18\x03 \x01(\x0e\x32*.frc2020.networking.DriveSignal.DemandType\"(\n\nDemandType\x12\x0c\n\x08OpenLoop\x10\x00\x12\x0c\n\x08Velocity\x10\x01\x62\x06proto3')
)



_DRIVESIGNAL_DEMANDTYPE = _descriptor.EnumDescriptor(
  name='DemandType',
  full_name='frc2020.networking.DriveSignal.DemandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OpenLoop', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Velocity', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=594,
  serialized_end=634,
)
_sym_db.RegisterEnumDescriptor(_DRIVESIGNAL_DEMANDTYPE)


_JETSONUPDATE = _descriptor.Descriptor(
  name='JetsonUpdate',
  full_name='frc2020.networking.JetsonUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_updates', full_name='frc2020.networking.JetsonUpdate.target_updates', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slam_update', full_name='frc2020.networking.JetsonUpdate.slam_update', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drive_signal', full_name='frc2020.networking.JetsonUpdate.drive_signal', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=230,
)


_VISIONTARGETSUPDATE_VISIONTARGET = _descriptor.Descriptor(
  name='VisionTarget',
  full_name='frc2020.networking.VisionTargetsUpdate.VisionTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_epoc', full_name='frc2020.networking.VisionTargetsUpdate.VisionTarget.frame_epoc', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='frc2020.networking.VisionTargetsUpdate.VisionTarget.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='frc2020.networking.VisionTargetsUpdate.VisionTarget.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='frc2020.networking.VisionTargetsUpdate.VisionTarget.theta', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=398,
)

_VISIONTARGETSUPDATE = _descriptor.Descriptor(
  name='VisionTargetsUpdate',
  full_name='frc2020.networking.VisionTargetsUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='targets', full_name='frc2020.networking.VisionTargetsUpdate.targets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VISIONTARGETSUPDATE_VISIONTARGET, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=398,
)


_SLAMPOSE = _descriptor.Descriptor(
  name='SLAMPose',
  full_name='frc2020.networking.SLAMPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_epoc', full_name='frc2020.networking.SLAMPose.update_epoc', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='frc2020.networking.SLAMPose.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='frc2020.networking.SLAMPose.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='frc2020.networking.SLAMPose.theta', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=468,
)


_DRIVESIGNAL = _descriptor.Descriptor(
  name='DriveSignal',
  full_name='frc2020.networking.DriveSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='demand_left', full_name='frc2020.networking.DriveSignal.demand_left', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demand_right', full_name='frc2020.networking.DriveSignal.demand_right', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demand_type', full_name='frc2020.networking.DriveSignal.demand_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRIVESIGNAL_DEMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=634,
)

_JETSONUPDATE.fields_by_name['target_updates'].message_type = _VISIONTARGETSUPDATE
_JETSONUPDATE.fields_by_name['slam_update'].message_type = _SLAMPOSE
_JETSONUPDATE.fields_by_name['drive_signal'].message_type = _DRIVESIGNAL
_VISIONTARGETSUPDATE_VISIONTARGET.containing_type = _VISIONTARGETSUPDATE
_VISIONTARGETSUPDATE.fields_by_name['targets'].message_type = _VISIONTARGETSUPDATE_VISIONTARGET
_DRIVESIGNAL.fields_by_name['demand_type'].enum_type = _DRIVESIGNAL_DEMANDTYPE
_DRIVESIGNAL_DEMANDTYPE.containing_type = _DRIVESIGNAL
DESCRIPTOR.message_types_by_name['JetsonUpdate'] = _JETSONUPDATE
DESCRIPTOR.message_types_by_name['VisionTargetsUpdate'] = _VISIONTARGETSUPDATE
DESCRIPTOR.message_types_by_name['SLAMPose'] = _SLAMPOSE
DESCRIPTOR.message_types_by_name['DriveSignal'] = _DRIVESIGNAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JetsonUpdate = _reflection.GeneratedProtocolMessageType('JetsonUpdate', (_message.Message,), {
  'DESCRIPTOR' : _JETSONUPDATE,
  '__module__' : 'jetson_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.JetsonUpdate)
  })
_sym_db.RegisterMessage(JetsonUpdate)

VisionTargetsUpdate = _reflection.GeneratedProtocolMessageType('VisionTargetsUpdate', (_message.Message,), {

  'VisionTarget' : _reflection.GeneratedProtocolMessageType('VisionTarget', (_message.Message,), {
    'DESCRIPTOR' : _VISIONTARGETSUPDATE_VISIONTARGET,
    '__module__' : 'jetson_message_pb2'
    # @@protoc_insertion_point(class_scope:frc2020.networking.VisionTargetsUpdate.VisionTarget)
    })
  ,
  'DESCRIPTOR' : _VISIONTARGETSUPDATE,
  '__module__' : 'jetson_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.VisionTargetsUpdate)
  })
_sym_db.RegisterMessage(VisionTargetsUpdate)
_sym_db.RegisterMessage(VisionTargetsUpdate.VisionTarget)

SLAMPose = _reflection.GeneratedProtocolMessageType('SLAMPose', (_message.Message,), {
  'DESCRIPTOR' : _SLAMPOSE,
  '__module__' : 'jetson_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.SLAMPose)
  })
_sym_db.RegisterMessage(SLAMPose)

DriveSignal = _reflection.GeneratedProtocolMessageType('DriveSignal', (_message.Message,), {
  'DESCRIPTOR' : _DRIVESIGNAL,
  '__module__' : 'jetson_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.DriveSignal)
  })
_sym_db.RegisterMessage(DriveSignal)


# @@protoc_insertion_point(module_scope)
