# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roborio_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='roborio_message.proto',
  package='frc2020.networking',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15roborio_message.proto\x12\x12\x66rc2020.networking\"\x80\x01\n\tRioUpdate\x12@\n\x0fodometry_update\x18\x01 \x01(\x0b\x32\'.frc2020.networking.WheelOdometryUpdate\x12\x31\n\ncode_state\x18\x02 \x01(\x0b\x32\x1d.frc2020.networking.CodeState\"F\n\x13WheelOdometryUpdate\x12\x12\n\ntime_stamp\x18\x01 \x01(\x02\x12\x0c\n\x04left\x18\x02 \x01(\x02\x12\r\n\x05right\x18\x03 \x01(\x02\"\x95\x01\n\tCodeState\x12\x11\n\tpre_start\x18\x01 \x01(\x08\x12\x41\n\renabled_state\x18\x02 \x01(\x0e\x32*.frc2020.networking.CodeState.EnabledState\"2\n\x0c\x45nabledState\x12\x0c\n\x08\x44isabled\x10\x00\x12\x08\n\x04\x41uto\x10\x01\x12\n\n\x06Tellop\x10\x02\x62\x06proto3')
)



_CODESTATE_ENABLEDSTATE = _descriptor.EnumDescriptor(
  name='EnabledState',
  full_name='frc2020.networking.CodeState.EnabledState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Disabled', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Auto', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Tellop', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=348,
  serialized_end=398,
)
_sym_db.RegisterEnumDescriptor(_CODESTATE_ENABLEDSTATE)


_RIOUPDATE = _descriptor.Descriptor(
  name='RioUpdate',
  full_name='frc2020.networking.RioUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='odometry_update', full_name='frc2020.networking.RioUpdate.odometry_update', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code_state', full_name='frc2020.networking.RioUpdate.code_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=174,
)


_WHEELODOMETRYUPDATE = _descriptor.Descriptor(
  name='WheelOdometryUpdate',
  full_name='frc2020.networking.WheelOdometryUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='frc2020.networking.WheelOdometryUpdate.time_stamp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left', full_name='frc2020.networking.WheelOdometryUpdate.left', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='frc2020.networking.WheelOdometryUpdate.right', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=246,
)


_CODESTATE = _descriptor.Descriptor(
  name='CodeState',
  full_name='frc2020.networking.CodeState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pre_start', full_name='frc2020.networking.CodeState.pre_start', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled_state', full_name='frc2020.networking.CodeState.enabled_state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CODESTATE_ENABLEDSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=398,
)

_RIOUPDATE.fields_by_name['odometry_update'].message_type = _WHEELODOMETRYUPDATE
_RIOUPDATE.fields_by_name['code_state'].message_type = _CODESTATE
_CODESTATE.fields_by_name['enabled_state'].enum_type = _CODESTATE_ENABLEDSTATE
_CODESTATE_ENABLEDSTATE.containing_type = _CODESTATE
DESCRIPTOR.message_types_by_name['RioUpdate'] = _RIOUPDATE
DESCRIPTOR.message_types_by_name['WheelOdometryUpdate'] = _WHEELODOMETRYUPDATE
DESCRIPTOR.message_types_by_name['CodeState'] = _CODESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RioUpdate = _reflection.GeneratedProtocolMessageType('RioUpdate', (_message.Message,), {
  'DESCRIPTOR' : _RIOUPDATE,
  '__module__' : 'roborio_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.RioUpdate)
  })
_sym_db.RegisterMessage(RioUpdate)

WheelOdometryUpdate = _reflection.GeneratedProtocolMessageType('WheelOdometryUpdate', (_message.Message,), {
  'DESCRIPTOR' : _WHEELODOMETRYUPDATE,
  '__module__' : 'roborio_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.WheelOdometryUpdate)
  })
_sym_db.RegisterMessage(WheelOdometryUpdate)

CodeState = _reflection.GeneratedProtocolMessageType('CodeState', (_message.Message,), {
  'DESCRIPTOR' : _CODESTATE,
  '__module__' : 'roborio_message_pb2'
  # @@protoc_insertion_point(class_scope:frc2020.networking.CodeState)
  })
_sym_db.RegisterMessage(CodeState)


# @@protoc_insertion_point(module_scope)
